function parsave(x0, y0, z0, v0, gamma0, psi0, qgt, qpt, d, restate)
RAD = 180/pi;
filename = sprintf('data/flight_x%d_y%d_z%d_v%d_gamma%d_psi%d_qgt%d_qpt%d_d%d.mat', ...
    round(x0), round(y0), round(z0), ...
    round(v0), round(gamma0*RAD), round(psi0*RAD), ...
    round(qgt*RAD), round(qpt*RAD), round(d));
save(filename, 'restate');
end
